// API Endpoints

export const API = process.env.REACT_APP_BASE_API_URL;

// Action consts
export const SET_AUTH = 'SET_AUTH';
export const AUTH_FAILED = 'AUTH_FAILED';
export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS';
export const GET_TRACKS_FAIL = 'GET_TRACKS_FAIL';
export const GET_TRACKS_DETAILS_SUCCESS = 'GET_TRACKS_DETAILS_SUCCESS';
export const GET_TRACKS_DETAILS_FAIL = 'GET_TRACKS_DETAILS_FAIL';
export const POST_TRACKS_SUCCESS = 'POST_TRACKS_SUCCESS';
export const POST_TRACKS_FAIL = 'POST_TRACKS_FAIL';
export const UPDATE_TRACKS_SUCCESS = 'UPDATE_TRACKS_SUCCESS';
export const UPDATE_TRACKS_FAIL = 'UPDATE_TRACKS_FAIL';
export const DELETE_TRACKS_SUCCESS = 'DELETE_TRACKS_SUCCESS';
export const DELETE_TRACKS_FAIL = 'DELETE_TRACKS_FAIL';